# See https://github.com/actions/labeler

"pkg: projectrc":
  - changed-files:
      - any-glob-to-any-file: packages/projectrc/**

"apps: www":
  - changed-files:
      - any-glob-to-any-file: www/**

🚨 schema:
  - changed-files:
      - any-glob-to-any-file: scripts/update-schema.ts
      - any-glob-to-any-file: packages/projectrc/schema.json
      - any-glob-to-any-file: packages/projectrc/src/schema.ts
