# See https://github.com/actions/labeler

"pkg: projectrc":
  - changed-files:
      - packages/projectrc/**

"apps: www":
  - changed-files:
      - www/**

🚨 schema:
  - changed-files:
      - scripts/update-schema.ts
      - packages/projectrc/schema.json
      - packages/projectrc/src/schema.ts
