# See https://github.com/actions/labeler

"pkg: projectrc":
  - packages/projectrc/**

"apps: www":
  - www/**

🚨 schema:
  - scripts/update-schema.ts
  - packages/projectrc/schema.json
  - packages/projectrc/src/schema.ts
