version: '3.9'

services:

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=toor
      - POSTGRES_USER=root
      - POSTGRES_DB=mosaic_db


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
