CREATE TABLE IF NOT EXISTS mosaic_repositories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  github_id VARCHAR NOT NULL UNIQUE,
  name_with_owner TEXT NOT NULL UNIQUE,
  description TEXT,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  config JSON NOT NULL DEFAULT '{}'
);
