[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[alias]
lint = "clippy --workspace --all-targets -- --deny warnings"

[target.'cfg(all())']
rustflags = [
  # CLIPPY LINT SETTINGS
  # This is a workaround to configure lints for the entire workspace, pending the ability to configure this via TOML.
  # See: `https://github.com/rust-lang/cargo/issues/5034`
  #      `https://github.com/EmbarkStudios/rust-ecosystem/issues/22#issuecomment-947011395`
  "-Wclippy::all", # all lints that are on by default (correctness, suspicious, style, complexity, perf)

    # restriction
  "-Wclippy::dbg_macro",
  # Disable this as semantics of `expect` and `Result` are different.
  # See: `https://github.com/web-infra-dev/rspack/pull/4848`
  # "-Wclippy::unwrap_in_result",
  "-Wclippy::unwrap_used",
  "-Wclippy::empty_drop",
  "-Wclippy::exit",
  "-Wclippy::empty_structs_with_brackets",
  "-Wclippy::rc_buffer",
  "-Wclippy::rc_mutex",
  "-Wclippy::same_name_method",

  "-Aclippy::default_constructed_unit_structs",
  "-C", "symbol-mangling-version=v0",
  "--cfg", "tokio_unstable"
]
