name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: install
        run: pnpm install

      - name: lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: install
        run: pnpm install

      - name: typecheck
        run: pnpm run typecheck
