name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - run: cargo build --release
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: cargo test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
